preserve_hierarchy: true
commit_message: "[ci skip]"

pull_request_title: "Sync Translations from Crowdin"
pull_request_labels: ["l10n"]
pull_request_reviewers: ["lazy-media"]

files:
  - source: /locales/en-US.po
    translation: /locales/%locale%.%file_extension%
