name: 🐞 Bug Report

description: Create a bug report to help improve Reactive Resume

title: "[Bug] <title>"
labels: [bug, v2, needs triage]
assignees: "lazy-media"

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: Yes, I have searched the existing issues and none of them match my problem.
          required: true

  - type: dropdown
    id: variant
    attributes:
      label: Product Variant
      description: What variant of Reactive Resume are you using?
      options:
        - Cloud (https://rxresume.org)
        - Self-Hosted
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug you're experiencing
      description: A detailed description of what you're experiencing. Please provide as much detail as possible as it will help me diagnose and fix the issue faster.
    validations:
      required: true

  - type: dropdown
    id: template
    attributes:
      label: What template are you using?
      description: Leave blank if the issue applies to all templates, or is not template-specific.
      multiple: false
      options:
        - Azurill
        - Bronzor
        - Chikorita
        - Ditto
        - Ditgar
        - Gengar
        - Glalie
        - Kakuna
        - Lapras
        - Leafish
        - Onyx
        - Pikachu
        - Rhyhorn
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
